weservr

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,19 +13,31 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
-      - name: Set up Docker
+      - name: Check and Install Docker
         run: |
-          sudo apt-get update
-          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
-          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
-          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
-          sudo apt-get update
-          sudo apt-get install -y docker-ce
-          sudo usermod -aG docker ${USER}
-          sudo systemctl enable docker
-          sudo systemctl start docker
-          sudo snap install docker 
-          sudo apt  install docker-compose -y
+          if ! command -v docker &> /dev/null; then
+            echo "Docker not found. Installing..."
+            sudo apt-get update
+            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
+            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
+            sudo apt-get update
+            sudo apt-get install -y docker-ce
+            sudo usermod -aG docker ${USER}
+            sudo systemctl enable docker
+            sudo systemctl start docker
+          else
+            echo "Docker is already installed."
+          fi
+
+      - name: Check and Install Docker Compose
+        run: |
+          if ! command -v docker-compose &> /dev/null; then
+            echo "Docker Compose not found. Installing..."
+            sudo snap install docker || sudo apt install docker-compose -y
+          else
+            echo "Docker Compose is already installed."
+          fi
 
       - name: Save SSH Key
         run: |
